"""Stable typed contracts shared by CrewAI and deterministic services."""

# This package is the single public re-export surface for domain contracts.
# ruff: noqa: F401

from crewai_app.domain.contracts.execution import (
    ACCEPTABLE_ALTERNATIVE_OWNER_MODEL_IDS,
    ApprovedExecutionRequest,
    BedrockModelId,
    DecisionRecord,
    DeterministicRiskDecision,
    ExchangeId,
    ExchangeNetwork,
    IndicatorTimeframe,
    MarketAnalysisSnapshot,
    MarketExecutionSnapshot,
    MarketLiquidityTier,
    OmittedStopLossDecision,
    PairBlacklistDecision,
    PairRiskLimit,
    SettlementAsset,
    TechnicalIndicatorSnapshot,
    TradingPairType,
    settlement_asset_for_exchange,
)
from crewai_app.domain.contracts.definitions import (
    AssetGroup,
    CanonicalTradeIntent,
    ClosedTradeOutcome,
    ConfidenceDecision,
    DeduplicationDecision,
    DeduplicationScope,
    ExchangeTradeState,
    FilterDecision,
    IngestionTransport,
    IntentType,
    LifecycleStrategySource,
    MinistralStrategyReviewSet,
    OwnerId,
    OwnerRagProfile,
    PerformanceMetricsSnapshot,
    PositionDirection,
    PositionLifecycleEvent,
    PositionLifecycleStrategy,
    PositionReductionHypothesis,
    PositionSizingDecision,
    QwenRagLabellingRecord,
    QwenSignalHypothesis,
    QwenStrategyCandidateSet,
    RagCurationSubmission,
    RagValidationMetadata,
    SerialRagExample,
    SignalEvaluationResult,
    StrategyOutcome,
    StrategyTier,
    StrategyTierPerformanceSummary,
    TakeProfitFillEvent,
    TakeProfitLevel,
    TakeProfitProtectionAction,
    TakeProfitProtectionDecision,
    TelegramAgentChannelConfig,
    TelegramAgentPollBatch,
    TelegramAgentRetrievalBatch,
    TelegramAgentRetrievedMessage,
    TelegramIngestionRecord,
    TelegramMessageEnvelope,
    TelegramPromptContext,
    TelegramPromptMessage,
    TelegramRagMessageReference,
    TestnetVenuePerformanceComparison,
    TradeAction,
    TradeCursorStatus,
    TradeThreadCursor,
    TradingMessageRelation,
    TradingMessageRelationDecision,
    TradingMessageSynonymDecision,
    VenuePerformanceSummary,
)

__all__ = [name for name in globals() if not name.startswith("_")]
